server:
  port: 8080


spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.0.128:3306/activitydemo
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      cache: false
      charset: <encoding> is added
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.mybatisdemo.model
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql